### ISSUE TITLE
Getting 2 url in the BannerImageUrl property

### ISSUE THREAD

**Issue by americo2015** [spplante/react-content-query#10]
Hi, 
When I try to query for pages with a banner image I get this response for the BannerImageUrl:

`https://tenant.sharepoint.com/_layouts/15/getpreview.ashx?guidSite=18413909-0b3e-4f55-ba0c-35ecb60721d4&guidWeb=0a95d1fa-6f11-432c-9231-aa46da033705&guidFile=fea63271-eaea-4753-8195-39a5c4a52763, https://tenant.sharepoint.com/_layouts/15/getpreview.ashx?guidSite=18413909-0b3e-4f55-ba0c-35ecb60721d4&guidWeb=0a95d1fa-6f11-432c-9231-aa46da033705&guidFile=fea63271-eaea-4753-8195-39a5c4a52763`

This response contains 2 url separated by a comma, the second url points to the image, the first one to a preview. 
If I want to show the page's banner image I have to use the second one but I can't find the way to fetch only the second url.

In the template I am using: `<img src="{{BannerImageUrl.textValue}}" />` 

How can I get the second url? 

Regards
Americo

**Comment by spplante** [comment]
@americo2015 I think the solution you are looking for is quite simple. If **BannerImageUrl** is an URL field, you can use the **rawValue** instead of the **textValue** which will return you an object with two properties : Url and Description.

So you would use the rawValue like this :

{{BannerImageUrl.rawValue.Url}}

For the future, you can use the {{log}} helper in your template to log any object in the browser’s console. So if ever you want to see the « rawValue » of your result to see what are your options, you can do the following in order to log the **items** array in the browser’s console :

{{log items}} 

That way you will be able to see **items** array directly in the console and inspect the textValue/htmlValue/rawValue for each elements of your array.

Let me know if that helps :)

**Comment by americo2015** [comment]
Hi,
Thanks, It worked perffectly. 
And also thanks for the tip about the log ( {{log items}} ) I was also looking for a way to print the object to the console.

Regards,
Americo

**Comment by spplante** [comment]
Glad I could help 👍

**Comment by dg2000r** [comment]
This helped me out too - thanks! One thing to add: by default {{BannerImageUrl.rawValue.Url}} returns a low res version of the image. You need to add a resolution parameter to get other versions. Values seem to go from 1 (low) to 6 (high)
eg. `<img src="{{BannerImageUrl.rawValue.Url}}&amp;resolution=6"/>`
