### ISSUE TITLE
Multiple lines of text

### ISSUE THREAD

**Issue by AmrHamam** [spplante/react-content-query#6]
How can i retrieve data from a column with type of "Multiple lines of text" and it is "Enhanced rich text (Rich text with pictures, tables, and hyperlinks)" without the HTML tags like normal content query webpart?

**Comment by spplante** [comment]
Hi AmrHamam, 

I just tested this, and using {{MyRichTextField.textValue}} does work for me. When displaying a field within the Handlebars template, you have to choose between the textValue, htmlValue and rawValue.

In the case of a multiple lines field with enhanced rich text, using the htmlValue or rawValue should render the HTML tags while using textValue should be rendering just the text.

Let me know if this helps

**Comment by spplante** [comment]
I am closing this issue as it should be supported using textValue like explained in my previous message. Feel free to reopen the if ever it does not work on your side.

**Comment by gristy58** [comment]
.htmlValue and .rawValue do not work. Whilst they retrieve the HTML content they just display it as text.

**Comment by spplante** [comment]
@gristy58 it does work, it is up to the user to decide if he wants to show the value as a regular string, or if he want Handlebars to evaluate it as HTML.

To tell Handlebars to evaluate a specific value as HTML, you simple have to use triple brackets instead of double brackets.

To render a value as a string :
```handlebars
{{MyField.htmlValue}}
```

To render a value as html :
```handlebars
{{{MyField.htmlValue}}}
```

As for the **rawValue**, if populated, that one will contain a JavaScript object so you have to know it’s properties, you can’t just output the whole object as a string as you will end-up with a string showing [object]

For example, hyperlink fields will give you an object which looks like this :

```javascript
{
    ‘’Url’’: ‘’https://google.com’’,
    ‘’Description’’: ‘’Link description...’’
}
```

So you would most likely use the **rawValue** like this :

```handlebars
{{MyLinkField.rawValue.Url}}
{{MyLinkField.rawValue.Description}}
```

If you want to know the properties of a particular rawValue before using it, you can simply do the following in order to ouput the rawValue in the browser’s console so you can check it’s properties :

```handlebars
{{log MyField}}
```

Or you can even output all the results by using this before the foreach :

```handlebars
{{log items}}
```

👍

**Comment by gristy58** [comment]
thanks that is awesome information, sorry i am a bit new with handlebars.

is there anyway to group with this webpart? i am a not much of a coder, but have made some really awesome things with this webpart. you have done a fantastic job.

**Comment by spplante** [comment]
You can createyour own handlebar helper in order to be able to group by, see [this post](https://github.com/SharePoint/sp-dev-fx-webparts/issues/1029)
